# Generated by Django 3.2.13 on 2023-10-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupYear',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
