# Generated by Django 3.2.13 on 2023-10-13 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231013_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupNumber',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='group',
            name='groupYear',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
