# Generated by Django 3.2.13 on 2023-10-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_work_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='returnNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
