# Generated by Django 3.2.13 on 2023-10-15 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_alter_work_returnnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='isEvaluate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
