# Generated by Django 3.2.13 on 2023-10-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20231015_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='returnNumber',
        ),
    ]
