# Generated by Django 3.2.13 on 2023-10-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workNumber',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
