# Generated by Django 3.2.13 on 2023-10-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_task_worknumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workNumber',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
