# Generated by Django 3.2.13 on 2023-10-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_task_worknumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='workNumber',
            new_name='number',
        ),
    ]
