# Generated by Django 3.2.13 on 2023-10-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20231015_2042'),
        ('teachers', '0005_rename_worknumber_task_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposedSolution', models.TextField()),
                ('mistakeDescription', models.TextField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.work')),
            ],
        ),
    ]
